server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    
  websocket:
    max-text-message-size: 8192
    max-binary-message-size: 4194304  # 4MB

logging:
  level:
    com.example.localshare: DEBUG
    org.springframework.web: INFO 